// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ-DtX901sIgHJwC6u77SZtRenKWKS3bg',
    appId: '1:1034357077558:web:8f475381ef2924d8490a97',
    messagingSenderId: '1034357077558',
    projectId: 'voyage-09',
    authDomain: 'voyage-09.firebaseapp.com',
    storageBucket: 'voyage-09.appspot.com',
    measurementId: 'G-HWK3SZ8NC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIMPGYmidBILdT_CbyyJqAWO5mdYw1kK4',
    appId: '1:1034357077558:android:68d35535ac42f9bf490a97',
    messagingSenderId: '1034357077558',
    projectId: 'voyage-09',
    storageBucket: 'voyage-09.appspot.com',
  );
}
